spring:
  profiles:
    active: local

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    org:
      springframework:
        web:
          servlet:
            handler:
              SimpleUrlHandlerMapping: WARN
      springframework.security: DEBUG

    com:
      fasterxml.jackson: DEBUG

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-time: 1800000 #30분
  refresh-token-time: 604800000 #7일간