spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URI}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}